server:
  host: 0.0.0.0
  port: 8090
  write-timeout: 60s
  read-timeout: 60s
  idle-timeout: 60s
  allowed-origins: ["*"]
  log-level: debug
  btc-net: "mainnet"
  max-content-length: 4096
  health-check-interval: 300 # 5 minutes interval
mongodb:
  address: "mongodb://mongodb:27017"
  db-name: xchains-api
  max-pagination-limit: 10
  db-batch-size-limit: 100
  logical-shard-count: 10
indexerdb:
  host: "postgresdb"
  port: 5432
  db-name: "xchains-indexer"
  user: "postgres"
  password: "postgres"
  log-level: "debug"

relayerdb:
  host: "relayer"
  port: 5432
  db-name: "relayer"
  user: "postgres"
  password: "postgres"
  log-level: "debug"

queue:
  queue_user: user # can be replaced by values in .env file
  queue_password: password
  url: "rabbitmq:5672"
  processing_timeout: 30
  msg_max_retry_attempts: 10
  requeue_delay_time: 300 # delay failed message requeue time in seconds
  queue_type: quorum
metrics:
  host: 0.0.0.0
  port: 2112
