server:
  host: 0.0.0.0
  port: 8090
  write-timeout: 60s
  read-timeout: 60s
  idle-timeout: 60s
  allowed-origins: ["*"]
  log-level: debug
  btc-net: "signet"
  max-content-length: 4096
  health-check-interval: 300 # 5 minutes interval

relayer-db:
  host: "192.168.1.21"
  port: 5432
  db-name: "relayer"
  user: "postgres"
  password: "postgres"
  log-level: "debug"


metrics:
  host: 0.0.0.0
  port: 2112
