definitions:
  gmp.ConfirmDocument:
    properties:
      block_timestamp:
        type: integer
      blockNumber:
        type: integer
      confirmation_txhash:
        type: string
      event:
        type: string
      poll_id:
        type: string
      sourceChain:
        type: string
      sourceTransactionHash:
        type: string
      transactionHash:
        type: string
      transactionIndex:
        type: integer
    type: object
  gmp.CreatedAtDocument:
    properties:
      day:
        type: integer
      hour:
        type: integer
      month:
        type: integer
      ms:
        type: integer
      quarter:
        type: integer
      week:
        type: integer
      year:
        type: integer
    type: object
  gmp.ExpressFeeDocument:
    properties:
      express_gas_overhead_fee:
        type: number
      express_gas_overhead_fee_usd:
        type: number
      relayer_fee:
        type: number
      relayer_fee_usd:
        type: number
      total:
        type: number
      total_usd:
        type: number
    type: object
  gmp.ExpressGasPriceRateDocument:
    properties:
      axelar_token:
        $ref: '#/definitions/gmp.TokenDocument'
      destination_native_token:
        $ref: '#/definitions/gmp.TokenDocument'
      ethereum_token:
        $ref: '#/definitions/gmp.TokenDocument'
      source_token:
        $ref: '#/definitions/gmp.TokenDocument'
    type: object
  gmp.FeesDocument:
    properties:
      axelar_token:
        $ref: '#/definitions/gmp.TokenDocument'
      base_fee:
        type: number
      destination_base_fee:
        type: number
      destination_base_fee_string:
        type: string
      destination_base_fee_usd:
        type: number
      destination_confirm_fee:
        type: number
      destination_express_fee:
        $ref: '#/definitions/gmp.ExpressFeeDocument'
      destination_native_token:
        $ref: '#/definitions/gmp.TokenDocument'
      ethereum_token:
        $ref: '#/definitions/gmp.TokenDocument'
      execute_gas_multiplier:
        type: number
      execute_min_gas_price:
        type: string
      express_execute_gas_multiplier:
        type: number
      express_fee:
        type: number
      express_fee_string:
        type: string
      express_fee_usd:
        type: number
      express_supported:
        type: boolean
      source_base_fee:
        type: number
      source_base_fee_usd:
        type: number
      source_confirm_fee:
        type: number
      source_express_fee:
        $ref: '#/definitions/gmp.ExpressFeeDocument'
      source_token:
        $ref: '#/definitions/gmp.TokenDocument'
    type: object
  gmp.GMPDocument:
    properties:
      approved:
        $ref: '#/definitions/gmp.GMPStepDocument'
      call:
        $ref: '#/definitions/gmp.GMPStepDocument'
      command_id:
        type: string
      confirm:
        $ref: '#/definitions/gmp.ConfirmDocument'
      confirm_failed:
        type: boolean
      confirm_failed_event:
        type: string
      day:
        type: integer
      execute_nonce:
        type: string
      execute_pending_transaction_hash:
        type: string
      executed:
        $ref: '#/definitions/gmp.GMPStepDocument'
      executing_at:
        type: integer
      express_gas_price_rate:
        $ref: '#/definitions/gmp.ExpressGasPriceRateDocument'
      fees:
        $ref: '#/definitions/gmp.FeesDocument'
      gas:
        $ref: '#/definitions/gmp.GasDocument'
      gas_paid:
        $ref: '#/definitions/gmp.GMPStepDocument'
      gas_price_rate:
        $ref: '#/definitions/gmp.ExpressGasPriceRateDocument'
      gas_status:
        type: string
      hour:
        type: integer
      id:
        type: string
      is_call_from_relayer:
        type: boolean
      is_execute_from_relayer:
        type: boolean
      is_insufficient_fee:
        type: boolean
      is_invalid_amount:
        type: boolean
      is_invalid_call:
        type: boolean
      is_invalid_contract_address:
        type: boolean
      is_invalid_destination_chain:
        type: boolean
      is_invalid_gas_paid:
        type: boolean
      is_invalid_gas_paid_mismatch_source_address:
        type: boolean
      is_invalid_payload_hash:
        type: boolean
      is_invalid_source_address:
        type: boolean
      is_invalid_symbol:
        type: boolean
      is_not_enough_gas:
        type: boolean
      is_two_way:
        type: boolean
      month:
        type: integer
      ms:
        type: integer
      not_enough_gas_to_execute:
        type: boolean
      quarter:
        type: integer
      refund_nonce:
        type: string
      refunded:
        $ref: '#/definitions/gmp.GMPStepDocument'
      refunding_at:
        type: integer
      simplified_status:
        type: string
      status:
        type: string
      time_spent:
        $ref: '#/definitions/gmp.TimeSpentDocument'
      to_refund:
        type: boolean
      week:
        type: integer
      year:
        type: integer
    type: object
  gmp.GMPStepDocument:
    properties:
      _logIndex:
        type: integer
      _type:
        type: string
      address:
        type: string
      block_timestamp:
        type: integer
      blockHash:
        type: string
      blockNumber:
        type: integer
      chain:
        type: string
      chain_type:
        type: string
      contract_address:
        type: string
      created_at:
        $ref: '#/definitions/gmp.CreatedAtDocument'
      destination_chain_type:
        type: string
      event:
        type: string
      eventIndex:
        type: integer
      eventSignature:
        type: string
      id:
        type: string
      logIndex:
        type: integer
      proposal_id:
        type: string
      receipt:
        $ref: '#/definitions/gmp.ReceiptDocument'
      removed:
        type: boolean
      returnValues:
        $ref: '#/definitions/gmp.ReturnValuesDocument'
      sourceChain:
        type: string
      topics:
        items:
          type: string
        type: array
      transaction:
        $ref: '#/definitions/gmp.TransactionDocument'
      transactionHash:
        type: string
      transactionIndex:
        type: integer
    type: object
  gmp.GasDocument:
    properties:
      gas_approve_amount:
        type: number
      gas_base_fee_amount:
        type: number
      gas_execute_amount:
        type: number
      gas_express_amount:
        type: number
      gas_express_fee_amount:
        type: number
      gas_paid_amount:
        type: number
      gas_remain_amount:
        type: number
      gas_used_amount:
        type: number
      gas_used_value:
        type: number
    type: object
  gmp.GasPriceInUnitsDocument:
    properties:
      decimals:
        type: integer
      value:
        type: string
    type: object
  gmp.LogDocument:
    properties:
      address:
        type: string
      blockHash:
        type: string
      blockNumber:
        type: integer
      data:
        type: string
      logIndex:
        type: integer
      removed:
        type: boolean
      topics:
        items:
          type: string
        type: array
      transactionHash:
        type: string
      transactionIndex:
        type: integer
    type: object
  gmp.ReceiptDocument:
    properties:
      blockHash:
        type: string
      blockNumber:
        type: integer
      confirmations:
        type: integer
      contractAddress:
        type: string
      cumulativeGasUsed:
        type: string
      effectiveGasPrice:
        type: string
      from:
        type: string
      gasUsed:
        type: string
      logs:
        items:
          $ref: '#/definitions/gmp.LogDocument'
        type: array
      status:
        type: integer
      to:
        type: string
      transactionHash:
        type: string
      transactionIndex:
        type: integer
      type:
        type: integer
    type: object
  gmp.ReturnValuesDocument:
    properties:
      commandId:
        type: string
      contractAddress:
        type: string
      destinationChain:
        type: string
      destinationContractAddress:
        type: string
      payload:
        type: string
      payloadHash:
        type: string
      sender:
        type: string
      sourceAddress:
        type: string
      sourceChain:
        type: string
      sourceEventIndex:
        type: string
      sourceTxHash:
        type: string
    type: object
  gmp.TimeSpentDocument:
    properties:
      approved_executed:
        type: integer
      call_approved:
        type: integer
      call_confirm:
        type: integer
      total:
        type: integer
    type: object
  gmp.TokenDocument:
    properties:
      contract_address:
        type: string
      decimals:
        type: integer
      gas_price:
        type: string
      gas_price_gwei:
        type: string
      gas_price_in_units:
        $ref: '#/definitions/gmp.GasPriceInUnitsDocument'
      name:
        type: string
      symbol:
        type: string
      token_price:
        $ref: '#/definitions/gmp.TokenPriceDocument'
    type: object
  gmp.TokenPriceDocument:
    properties:
      usd:
        type: number
    type: object
  gmp.TransactionDocument:
    properties:
      blockHash:
        type: string
      blockNumber:
        type: integer
      chainId:
        type: integer
      from:
        type: string
      gas:
        type: string
      gasPrice:
        type: string
      hash:
        type: string
      maxFeePerGas:
        type: string
      maxPriorityFeePerGas:
        type: string
      nonce:
        type: integer
      r:
        type: string
      s:
        type: string
      to:
        type: string
      transactionIndex:
        type: integer
      type:
        type: integer
      v:
        type: integer
      value:
        type: integer
      yParity:
        type: string
    type: object
  handlers.CreateDAppRequestPayload:
    properties:
      access_token:
        type: string
      btc_address_hex:
        type: string
      chain_endpoint:
        type: string
      chain_id:
        type: string
      chain_name:
        type: string
      custodial_group_id:
        type: integer
      public_key_hex:
        type: string
      rpc_url:
        type: string
      smart_contract_address:
        description: 'UPDATE: New field'
        type: string
      token_contract_address:
        type: string
    type: object
  handlers.GmpPublicResponse-array_gmp_GMPDocument:
    properties:
      data:
        items:
          $ref: '#/definitions/gmp.GMPDocument'
        type: array
      total:
        type: integer
    type: object
  handlers.IdRequestPayload:
    properties:
      id:
        type: string
    type: object
  handlers.PublicResponse-array_models_DApp:
    properties:
      data:
        items:
          $ref: '#/definitions/models.DApp'
        type: array
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-array_vault_VaultDocument:
    properties:
      data:
        items:
          $ref: '#/definitions/vault.VaultDocument'
        type: array
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-handlers_CreateDAppRequestPayload:
    properties:
      data:
        $ref: '#/definitions/handlers.CreateDAppRequestPayload'
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-handlers_IdRequestPayload:
    properties:
      data:
        $ref: '#/definitions/handlers.IdRequestPayload'
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-handlers_UpdateDAppRequestPayload:
    properties:
      data:
        $ref: '#/definitions/handlers.UpdateDAppRequestPayload'
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-services_GlobalParamsPublic:
    properties:
      data:
        $ref: '#/definitions/services.GlobalParamsPublic'
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.UpdateDAppRequestPayload:
    properties:
      access_token:
        type: string
      btc_address_hex:
        type: string
      chain_endpoint:
        type: string
      chain_id:
        type: string
      chain_name:
        type: string
      custodial_group_id:
        type: integer
      id:
        type: string
      public_key_hex:
        type: string
      rpc_url:
        type: string
      smart_contract_address:
        description: 'UPDATE: New field'
        type: string
      token_contract_address:
        type: string
    type: object
  handlers.paginationResponse:
    properties:
      next_key:
        type: string
    type: object
  models.Custodial:
    properties:
      btcPublicKeyHex:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.CustodialGroup:
    properties:
      custodials:
        items:
          $ref: '#/definitions/models.Custodial'
        type: array
      id:
        type: integer
      name:
        type: string
      quorum:
        type: integer
      taprootAddress:
        description: Calculate from BtcPublicKeyHex of each Custodials
        type: string
    type: object
  models.DApp:
    properties:
      accessToken:
        type: string
      btcaddressHex:
        type: string
      chainEndpoint:
        type: string
      chainID:
        type: string
      chainName:
        type: string
      custodialGroup:
        $ref: '#/definitions/models.CustodialGroup'
      id:
        type: string
      publicKeyHex:
        type: string
      rpcurl:
        type: string
      smartContractAddress:
        type: string
      state:
        type: boolean
      tokenContractAddress:
        type: string
    type: object
  services.GlobalParamsPublic:
    properties:
      versions:
        items:
          $ref: '#/definitions/services.VersionedGlobalParamsPublic'
        type: array
    type: object
  services.VersionedGlobalParamsPublic:
    properties:
      activation_height:
        type: integer
      cap_height:
        type: integer
      confirmation_depth:
        type: integer
      covenant_pks:
        items:
          type: string
        type: array
      covenant_quorum:
        type: integer
      max_staking_amount:
        type: integer
      max_staking_time:
        type: integer
      min_staking_amount:
        type: integer
      min_staking_time:
        type: integer
      staking_cap:
        type: integer
      tag:
        type: string
      unbonding_fee:
        type: integer
      unbonding_time:
        type: integer
      version:
        type: integer
    type: object
  vault.VaultDocument:
    properties:
      amount:
        type: string
      created_at:
        type: integer
      destination_chain:
        type: string
      destination_smart_contract_address:
        type: string
      executed_amount:
        type: string
      executed_ref_tx_hash:
        type: string
      id:
        type: string
      simplified_status:
        type: string
      source_chain:
        type: string
      source_tx_hash:
        type: string
      source_tx_hex:
        type: string
      staker_pubkey:
        type: string
      status:
        type: string
      updated_at:
        type: integer
    type: object
info:
  contact: {}
paths:
  /healthcheck:
    get:
      description: Health check the service, including ping database connection
      produces:
      - application/json
      responses:
        "200":
          description: Server is up and running
          schema:
            type: string
      summary: Health check endpoint
  /v1/dApp:
    delete:
      description: Deletes a dApp
      produces:
      - application/json
      responses:
        "200":
          description: Delete successfully
          schema:
            type: string
      summary: Delete dApp
      tags:
      - dApp
    get:
      description: Retrieves all dApps
      produces:
      - application/json
      responses:
        "200":
          description: List of dApps
          schema:
            $ref: '#/definitions/handlers.PublicResponse-array_models_DApp'
      summary: Get dApps
      tags:
      - dApp
    patch:
      description: Toggles a dApp
      produces:
      - application/json
      responses:
        "200":
          description: Toggled dApp
          schema:
            $ref: '#/definitions/handlers.PublicResponse-handlers_IdRequestPayload'
      summary: Toggle dApp
      tags:
      - dApp
    post:
      consumes:
      - application/json
      description: Creates a new dApp
      produces:
      - application/json
      responses:
        "200":
          description: Created dApp
          schema:
            $ref: '#/definitions/handlers.PublicResponse-handlers_CreateDAppRequestPayload'
      summary: Create dApp
      tags:
      - dApp
    put:
      description: Updates a dApp
      produces:
      - application/json
      responses:
        "200":
          description: Updated dApp
          schema:
            $ref: '#/definitions/handlers.PublicResponse-handlers_UpdateDAppRequestPayload'
      summary: Update dApp
      tags:
      - dApp
  /v1/global-params:
    get:
      description: Retrieves the global parameters for Scalar, including finality
        provider details.
      produces:
      - application/json
      responses:
        "200":
          description: Global parameters
          schema:
            $ref: '#/definitions/handlers.PublicResponse-services_GlobalParamsPublic'
      summary: Get Scalar global parameters
  /v1/gmp/searchGMP:
    post:
      consumes:
      - application/json
      description: Search for GMP transactions with filters
      produces:
      - application/json
      responses:
        "200":
          description: List of GMP
          schema:
            $ref: '#/definitions/handlers.GmpPublicResponse-array_gmp_GMPDocument'
      summary: Search GMP transactions
      tags:
      - gmp
  /v1/vault/searchVault:
    post:
      consumes:
      - application/json
      description: Searches for vaults based on the provided payload
      produces:
      - application/json
      responses:
        "200":
          description: List of vaults
          schema:
            $ref: '#/definitions/handlers.PublicResponse-array_vault_VaultDocument'
      summary: Search vaults
      tags:
      - vault
swagger: "2.0"
